name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  # Bước 1: Phân tích môi trường (Environment Check)
  setup:
    runs-on: ubuntu-latest
    outputs:
      env_tag: ${{ steps.set-tag.outputs.ENV_TAG }}
    steps:
      - id: set-tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENV_TAG=prod" >> $GITHUB_OUTPUT
          else
            echo "ENV_TAG=staging" >> $GITHUB_OUTPUT
          fi

  # Bước 2: Gọi Logic Build (Mục 2, 3, 4 đã trình bày)
  call-build:
    needs: setup
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: hkduy/devopsexample
      env_tag: ${{ needs.setup.outputs.env_tag }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # Bước 3: Gọi Logic Deploy (Mục 1 đã trình bày)
  call-deploy:
    needs: [setup, call-build]
    # Chỉ deploy nếu là nhánh main (Production)
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      env_name: "Production"